#!/bin/bash

[ "$TEST_VERBOSE" ] || export TEST_VERBOSE=0

mkdir -p files
dd if=/dev/zero of=files/128KiB-16 bs=131056 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/640KiB-16 bs=655344 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/768KiB-16 bs=804848 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/896KiB-16 bs=917488 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/1024KiB bs=1048576 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/1024KiB-16 bs=1048560 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/1024KiB-32 bs=1048544 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/1280KiB+4 bs=1310724 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/4096KiB bs=4194304 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/6528KiB bs=6684672 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/6528KiB+16 bs=6684688 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/6656KiB-16 bs=6815728 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/6656KiB bs=6815744 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/14720KiB bs=15073280 count=1	 > /dev/null 2>&1
dd if=/dev/zero of=files/14720KiB+16 bs=15073296 count=1 > /dev/null 2>&1
dd if=/dev/zero of=files/14720KiB-16 bs=15073264 count=1 > /dev/null 2>&1
dd if=/dev/zero of=files/14847KiB bs=15204336 count=1	 > /dev/null 2>&1

export NONINTERACTIVE="yes"
for test in `find . -name "*.test" | grep -v ^./broken/`; do
	test="${test/.test}"
	echo -n "Running test $test... "
	if $(./do-test $test > /dev/null); then
		echo "ok"
	else
		echo "not ok"
		FAIL=1
	fi
done
if [ -e broken ]; then
	for broken in `find broken -name "*.test"`; do
		echo "Warning: $broken exists"
	done
fi

rm -rf files

if [ $FAIL ]; then
	exit 1
else
	exit 0
fi

